USE [master]
GO

/****** Object:  Database [EducomOpdrachtAPI]    Script Date: 24-6-2021 16:47:06 ******/
CREATE DATABASE [EducomOpdrachtAPI]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EducomOpdrachtAPI', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\EducomOpdrachtAPI.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EducomOpdrachtAPI_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\EducomOpdrachtAPI_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EducomOpdrachtAPI].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EducomOpdrachtAPI] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET ARITHABORT OFF 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET  ENABLE_BROKER 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET  MULTI_USER 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EducomOpdrachtAPI] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EducomOpdrachtAPI] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [EducomOpdrachtAPI] SET QUERY_STORE = OFF
GO

ALTER DATABASE [EducomOpdrachtAPI] SET  READ_WRITE 
GO

CREATE TABLE [EducomOpdrachtAPI].[dbo].[Weerstations](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[StationId] [bigint] NOT NULL,
	[Date] [datetime2](7) NOT NULL,
	[Region] [nvarchar](max) NULL,
	[Name] [nvarchar](max) NULL,
	[TemperatureGc] [float] NOT NULL,
	[TemperatureCm] [float] NOT NULL,
	[WindspeedMs] [float] NOT NULL,
	[WindspeedBf] [int] NOT NULL,
	[Humidity] [int] NOT NULL,
	[AirPressure] [float] NOT NULL,
 CONSTRAINT [PK_Weerstations] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

CREATE TABLE [EducomOpdrachtAPI].[dbo].[Weerberichten](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Date] [datetime2](7) NOT NULL,
	[MaxTemperature] [int] NOT NULL,
	[MinTemperature] [int] NOT NULL,
	[Windspeed] [int] NOT NULL,
	[RainChance] [int] NOT NULL,
	[SunChance] [int] NOT NULL,
 CONSTRAINT [PK_Weerberichten] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

EXEC EducomOpdrachtAPI..sp_addsrvrolemember @loginame = N'NT AUTHORITY\SYSTEM', @rolename = N'sysadmin'
GO